### ISSUE TITLE
Page to view Podcast in index

### ISSUE THREAD

**Issue by stevencrader** [Podcastindex-org/web-ui#15]
Its been discussed on the mastodon and podcast that there is a request to have a page on podcastindex.org to view the podcast data.

Here are my thoughts about the features the page should have. Please add or suggest additional ideas below

  - URL: podcastindex.org/podcast/<id>
  - Link to page from search results
  - Display (at a minimum) the same fields shown in the results page
  - Display the most recent episodes

**Comment by stevencrader** [comment]
I've started working on the first version of this.

**Comment by daveajones** [comment]
That would be a great start.  I can't think of anything else at the moment.

**Comment by drunkplato** [comment]
When I made the first version of the `PodcastPlayer` component, I made it for the carousel, but I am sure you could make adjustments so that it could take a single or multiple episodes. That way we could utilize the same look and feel. Or perhaps a `carousel` prop could be used?

Looking forward to seeing what you come up with!
