### ISSUE TITLE
No Open Graph tags

### ISSUE THREAD

**Issue by henkvantijen** [Podcastindex-org/web-ui#173]
Hi , when pasting an URL of a podcast page of Pi , I don’t see a preview. Are ‘Open Graph tags’ missing? On purpose?

Example: this url does not trigger Telegram to fetch and generate a preview. 
https://podcastindex.org/podcast/1015378

**Comment by daveajones** [comment]
Thanks!

**Comment by stevencrader** [comment]
I looked at resolving this today. It is easy to add/update the necessary meta tags but it doesn't resolve the issue since the preview looks at the static index.html and not the rendered content since it is all done server side.

There are services (like https://prerender.io/) that can serve prerendered data but I'm not sure it would work for us and it has a fee associated. 

If someone knows a better way to do this, please share.

**Comment by zoul** [comment]
Next.js has a nice way to solve this:

https://nextjs.org/docs/api-reference/next/head

It’s a nice React framework overall, I can recommend it heartily. (I perfectly understand if that’s not a reasonable suggestion here.)

**Comment by dellagustin** [comment]
There is a bit of active server code at `./server`.
One way would be to have code there that checks the route, consume the API and injects the data into the `index.html`. Take it as brainstorming, I have no practical experience with this.
