### ISSUE TITLE
[Value] Add WebLN support

### ISSUE THREAD

**Issue by MaxHillebrand** [Podcastindex-org/web-ui#62]
First of all, what you've built is absolutely incredible, great work, thank You!

---

podcastindex.org has the web player, and it would be great if the listener can pay those nodes in the value field even when listening through this web client.

Adding a browser lightning wallet to the website is certainly a bad idea.

However, there are [browser extension lightning wallets](https://github.com/joule-labs/joule-extension/) [usually connected to a remote ln node], which can pick up an invoice displayed on a website, then pop-up the browser extension for user confirmation. Optionally the user can also set an upfront agreed upon "allowance" to a certain website.

This works with the [WebLN](https://github.com/joule-labs/webln) stack, which is "a way of interacting with a user's Lightning node via the browser." I'm not too familiar with the nuances of the spec, but I think it would require little work [non-dev-speak] on the podcastindex.org site, other than displaying the ln keysend invoice in the particular WebLN format. I am also not sure how to optimize this for streaming payments.

@bumi might know more details on how to get it done.

**Comment by bumi** [comment]
thanks for opening that topic @MaxHillebrand 
I think that's a great example of how a WebLN spec could bring nice lightning functionality to the web.

WebLN defines a simple JavaScript spec how a website can interact with lightning (e.g. request a payment, or request an invoice). 
Wallets (e.g. a browser extension) inject such a standard webln object in the website and make it available in JS.

Example usage: 

```js
webln.sendPayment(paymentRequest)
  .then(response => {

  })
  .catch(error => { 
    handleFallback(); 
  });
```

The player can simple do that call periodically or on some user interaction. Because it is plain JS anything is possible. 
WebLN is an unobtrusive enhancement, so if users do not support it they simply get a the fallback, e.g. manually displaying payment details. 

WebLN was first released 2 years ago and is implemented by quite some websites (e.g. bitrefill) and wallets (e.g. bluewallet). But it needs an update for newer lightning features. For this it would be great to hear your thoughts on this. 

I am happy to work on a PR to integrate actual donation payments for the podcast value fields.

**Comment by stevencrader** [comment]
I think this can be closed. Support for webln was added in #189

**Comment by MaxHillebrand** [comment]
That's awesome progress, thanks!
